//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doantotnghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int MaCTDH { get; set; }
        public int MaDH { get; set; }
        public int MaSP { get; set; }
        public int TongTien { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> GiaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<System.DateTime> Ngaygiao { get; set; }
    
        public virtual Account_KhachHang Account_KhachHang { get; set; }
        public virtual DonHang DonHang { get; set; }
        public virtual DonHang DonHang1 { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual SanPham SanPham1 { get; set; }
    }
}
