//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doantotnghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
<<<<<<< HEAD
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.ChiTietDonHangs1 = new HashSet<ChiTietDonHang>();
=======
>>>>>>> 997f9b8680ef12397472517faa815b8e795d0eee
            this.ChiTietGioHangs = new HashSet<ChiTietGioHang>();
            this.ChiTietGioHangs1 = new HashSet<ChiTietGioHang>();
            this.HuyHangs = new HashSet<HuyHang>();
            this.NhanXetSanPhams = new HashSet<NhanXetSanPham>();
            this.NhapHangs = new HashSet<NhapHang>();
<<<<<<< HEAD
=======
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.ChiTietDonHangs1 = new HashSet<ChiTietDonHang>();
>>>>>>> 997f9b8680ef12397472517faa815b8e795d0eee
        }
    
        public int MaSP { get; set; }
        public Nullable<int> MaDM { get; set; }
        public string TenSP { get; set; }
        public string AnhSP { get; set; }
        public int GiaSP { get; set; }
        public bool TrangThai { get; set; }
        public string MotaSP { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public Nullable<System.DateTime> NgayHuy { get; set; }
        public string DonViTinh { get; set; }
        public int TonKho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
<<<<<<< HEAD
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
=======
>>>>>>> 997f9b8680ef12397472517faa815b8e795d0eee
        public virtual ICollection<ChiTietGioHang> ChiTietGioHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGioHang> ChiTietGioHangs1 { get; set; }
        public virtual DanhMucSP DanhMucSP { get; set; }
        public virtual DanhMucSP DanhMucSP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HuyHang> HuyHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanXetSanPham> NhanXetSanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhapHang> NhapHangs { get; set; }
<<<<<<< HEAD
=======
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs1 { get; set; }
>>>>>>> 997f9b8680ef12397472517faa815b8e795d0eee
    }
}
