//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doantotnghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuyHang
    {
        public int MaHuyDonHang { get; set; }
        public int MaSP { get; set; }
        public int SoLuongHuy { get; set; }
        public string LyDoHuy { get; set; }
        public System.DateTime NgayHuy { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
